Instance: sdc-form-designer
InstanceOf: CapabilityStatement
Title: "SDC Form Designer"
Description: "SDC Form authoring system"
Usage: #definition
* url = "http://hl7.org/fhir/uv/sdc/CapabilityStatement/sdc-form-designer"
* name = "SDCFormDesigner"
* title = "SDC Form Designer"
* status = #active
* date = "2014-07-06"
* description = "This profile defines the expected capabilities of the *SDC Form Designer* role when conforming to this implementation guide.  This role is responsible for defining forms ([[[Questionnaire]]] resource instances) that include references to [[[StructureDefinition]]] resouces containing data elements that define the meaning of particular questions and can be used to aid in pre-populating and auto-populating forms."
* kind = #requirements
* fhirVersion = #4.0.1
* format[+] = #xml
* format[+] = #json
* rest
  * mode = #client
  * documentation = "The [[[Questionnaire]]] resource is used to create and maintain SDC-compliant forms.  The [[[StructureDefinition]]] resource is used to look-up existing data elements that can be referenced in forms.  Optionally, [[[StructureDefinition]]]s can also be created and maintained in conjunction with form editing.  This is an optional feature as not all environments will provide support for data element definitions from form authors.  The [[[ValueSet]]] and [[[CodeSystem]]] resources are used to capture allowed values for questions that are to be answered from a pre-defined list of values.  For some forms, some or all of the referenced value sets (and possibly code systems) will be handled as 'contained' resources, meaning the value set exists only in the context of the [[[Questionnaire]]] and cannot be referenced or maintained without also updating the form.  However, systems should support value set and code system re-use across questionnaires.  (Version-specific referencing can be used to avoid value sets from changing independent of the referencing [[[Questionnaire]]].)"
  * security.description = "Implementations must meet the [general security requirements](security.html) documented in this implementation guide.html."
  * insert SDCResource(Questionnaire, #SHALL, sdc-questionnaire, [[Form Designers are responsible for handling form discovery and management.]])
    * insert Interaction(#SHALL, #search-type, "Allows discovery of existing questionnaires for editing")
    * insert Interaction(#SHALL, #read, "Allows retrieval of a specific questionnaire by id")
    * insert Interaction(#SHALL, #create, "Allows submission of a new form design")
    * insert Interaction(#SHALL, #update, "Allows revision of an existing form design.  Note that certain types of updates may necessitate retiring the existing form and defining a new one.")
    * insert Interaction(#MAY, #history-instance, "Allows review of changes to a questionnaire over time")
    * insert Interaction(#MAY, #vread, "Allows retrieval of a historical version of a questionnaire")
    * insert Interaction(#MAY, #delete, "Not all servers will support deletion of forms.  Status change to 'retired' will be more typical\, though deletion of draft profiles may keep repositories cleaner.")
    * insert SearchParam(#SHALL, "url", #uri, http://hl7.org/fhir/SearchParameter/Questionnaire-url)
    * insert SearchParam(#SHALL, "version", #token, http://hl7.org/fhir/SearchParameter/Questionnaire-version)
    * insert SearchParam(#SHALL, "status", #token, http://hl7.org/fhir/SearchParameter/Questionnaire-status)
    * insert SearchParam(#SHALL, "experimental", #token, http://hl7.org/fhir/uv/sdc/SearchParameter/canonical-experimental)
    * insert SearchParam(#SHOULD, "context-type-quantity", #composite, http://hl7.org/fhir/SearchParameter/Questionnaire-context-type-quantity)
    * insert SearchParam(#SHOULD, "context-type-value", #composite, http://hl7.org/fhir/SearchParameter/Questionnaire-context-type-value)
    * insert SearchParam(#SHOULD, "date", #date, http://hl7.org/fhir/SearchParameter/Questionnaire-date)
    * insert SearchParam(#SHOULD, "definition", #uri, http://hl7.org/fhir/SearchParameter/Questionnaire-definition)
    * insert SearchParam(#SHOULD, "description", #string, http://hl7.org/fhir/SearchParameter/Questionnaire-description)
    * insert SearchParam(#SHOULD, "identifier", #token, http://hl7.org/fhir/SearchParameter/Questionnaire-identifier)
    * insert SearchParam(#SHOULD, "publisher", #string, http://hl7.org/fhir/SearchParameter/Questionnaire-publisher)
    * insert SearchParam(#SHOULD, "questionnaire-code", #token, http://hl7.org/fhir/uv/sdc/SearchParameter/Questionnaire-questionnaire-code)
    * insert SearchParam(#SHOULD, "code", #token, http://hl7.org/fhir/SearchParameter/Questionnaire-code)
    * insert SearchParam(#SHOULD, "combo-code", #token, http://hl7.org/fhir/uv/sdc/SearchParameter/Questionnaire-combo-code)
    * insert SearchParam(#SHOULD, "subject-type", #token, http://hl7.org/fhir/uv/sdc/SearchParameter/Questionnaire-subject-type)
    * insert SearchParam(#SHOULD, "title", #string, http://hl7.org/fhir/SearchParameter/Questionnaire-title)
    * insert SearchParam(#MAY, "effective", #date, http://hl7.org/fhir/SearchParameter/Questionnaire-effective)
    * insert SearchParam(#MAY, "jurisdiction", #token,http://hl7.org/fhir/SearchParameter/Questionnaire-jurisdiction)
    * insert SearchParam(#MAY, "assemble-expectation", #token, http://hl7.org/fhir/uv/sdc/SearchParameter/questionnaire-assemble-expectation)
    * insert SearchParam(#MAY, "assembled-from", #reference, http://hl7.org/fhir/uv/sdc/SearchParameter/questionnaire-assembled-from)
  * insert SDCResource(ValueSet, #SHOULD, sdc-valueset, [[Form Designers will usually need to find and manage value sets\, whether on a Form Manager or an external terminology service.]])
    * insert Interaction(#SHALL, #search-type, "Allows discovery of existing value sets for use by questions in a form")
    * insert Interaction(#SHALL, #read, "Allows retrieval of details if search does not or after a create or update if the server makes changes")
    * insert Interaction(#SHALL, #create, "Allows definition of a new value set used by one or more questions")
    * insert Interaction(#SHALL, #update, "Allows existing value sets referenced by a form to be maintained.  Note that certain types of updates may necessitate retiring the existing value set and defining a new one.")
    * insert Interaction(#SHOULD, #delete, "Not all servers will support deletion of value sets.  Status change to 'retired' will be more typical\, though deletion of draft value sets may keep repositories cleaner.")
    * insert Interaction(#MAY, #history-instance, "Allows review of changes to a value set over time")
    * insert Interaction(#MAY, #vread, "Allows retrieval of a historical version of a value set")
    * insert SearchParam(#SHALL, "url", #uri, http://hl7.org/fhir/SearchParameter/conformance-url)
    * insert SearchParam(#SHALL, "version", #token, http://hl7.org/fhir/SearchParameter/conformance-version)
    * insert SearchParam(#SHALL, "experimental", #token, http://hl7.org/fhir/uv/sdc/SearchParameter/canonical-experimental)
    * insert SearchParam(#SHALL, "status", #token, http://hl7.org/fhir/SearchParameter/conformance-status)
    * insert SearchParam(#SHALL, "reference", #uri, http://hl7.org/fhir/SearchParameter/ValueSet-reference)
    * insert SearchParam(#SHOULD, "date", #date, http://hl7.org/fhir/SearchParameter/conformance-date)
    * insert SearchParam(#SHOULD, "context-type-quantity", #composite, http://hl7.org/fhir/SearchParameter/conformance-context-type-quantity)
    * insert SearchParam(#SHOULD, "context-type-value", #composite, http://hl7.org/fhir/SearchParameter/conformance-context-type-value)
    * insert SearchParam(#SHOULD, "identifier", #token, http://hl7.org/fhir/SearchParameter/conformance-identifier)
    * insert SearchParam(#SHOULD, "title", #string, http://hl7.org/fhir/SearchParameter/conformance-title)
    * insert SearchParam(#MAY, "description", #string, http://hl7.org/fhir/SearchParameter/conformance-description)
    * insert SearchParam(#MAY, "jurisdiction", #token, http://hl7.org/fhir/SearchParameter/conformance-jurisdiction)
    * insert SearchParam(#MAY, "publisher", #string, http://hl7.org/fhir/SearchParameter/conformance-publisher)
  * insert SDCResource(CodeSystem, #SHOULD, sdc-codesystem, [[Form Designers will usually need to find and manage code systems\, whether on a Form Manager or an external terminology service.]])
    * insert Interaction(#SHALL, #search-type, "Allows discovery of existing code systems for use by questions in a form")
    * insert Interaction(#SHALL, #create, "Allows definition of a new code system used by one or more questions")
    * insert Interaction(#SHALL, #update, "Allows existing code systems referenced by a form to be maintained.  Note that certain types of updates may necessitate retiring the existing code system and defining a new one.")
    * insert Interaction(#SHOULD, #delete, "Not all servers will support deletion of code systems.  Status change to 'retired' will be more typical\, though deletion of draft code systems may keep repositories cleaner.")
    * insert Interaction(#MAY, #read, "Allows retrieval of details if search does not or after a create or update if the server makes changes")
    * insert Interaction(#MAY, #history-instance, "Allows review of changes to a code system over time")
    * insert Interaction(#MAY, #vread, "Allows retrieval of a historical version of a code system")
    * insert SearchParam(#SHALL, "url", #uri, http://hl7.org/fhir/SearchParameter/conformance-url)
    * insert SearchParam(#SHALL, "version", #token, http://hl7.org/fhir/SearchParameter/conformance-version)
    * insert SearchParam(#SHALL, "experimental", #token, http://hl7.org/fhir/uv/sdc/SearchParameter/canonical-experimental)
    * insert SearchParam(#SHALL, "status", #token, http://hl7.org/fhir/SearchParameter/conformance-status)
    * insert SearchParam(#SHALL, "content-mode", #token, http://hl7.org/fhir/SearchParameter/CodeSystem-content-mode)
    * insert SearchParam(#SHOULD, "date", #date, http://hl7.org/fhir/SearchParameter/conformance-date)
    * insert SearchParam(#SHOULD, "context-type-quantity", #composite, http://hl7.org/fhir/SearchParameter/conformance-context-type-quantity)
    * insert SearchParam(#SHOULD, "context-type-value", #composite, http://hl7.org/fhir/SearchParameter/conformance-context-type-value)
    * insert SearchParam(#SHOULD, "identifier", #token, http://hl7.org/fhir/SearchParameter/conformance-identifier)
    * insert SearchParam(#SHOULD, "supplements", #reference, http://hl7.org/fhir/SearchParameter/CodeSystem-supplements)
    * insert SearchParam(#SHOULD, "title", #string, http://hl7.org/fhir/SearchParameter/conformance-title)
    * insert SearchParam(#MAY, "description", #string, http://hl7.org/fhir/SearchParameter/conformance-description)
    * insert SearchParam(#MAY, "jurisdiction", #token, http://hl7.org/fhir/SearchParameter/conformance-jurisdiction)
    * insert SearchParam(#MAY, "publisher", #string, http://hl7.org/fhir/SearchParameter/conformance-publisher)
    * insert SearchParam(#MAY, "language", #token, http://hl7.org/fhir/SearchParameter/CodeSystem-language)
  * insert SDCResource(Library, #SHOULD, sdc-library, [[Allows managing libraries relevant to population\, extraction\, or other logic]])
    * insert Interaction(#SHALL, #search-type, "Allows discovery of existing libraries for use by questions in a form")
    * insert Interaction(#SHALL, #create, "Allows definition of a new library used by one or more questions")
    * insert Interaction(#SHALL, #update, "Allows existing libraries referenced by a form to be maintained.  Note that certain types of updates may necessitate retiring the existing library and defining a new one.")
    * insert Interaction(#SHOULD, #delete, "Not all servers will support deletion of libraries.  Status change to 'retired' will be more typical\, though deletion of draft libraries may keep repositories cleaner.")
    * insert Interaction(#MAY, #read, "Allows retrieval of details if search does not or after a create or update if the server makes changes")
    * insert Interaction(#MAY, #history-instance, "Allows review of changes to a library over time")
    * insert Interaction(#MAY, #vread, "Allows retrieval of a historical version of a library")
    * insert SearchParam(#SHALL, "url", #uri, http://hl7.org/fhir/SearchParameter/Library-url)
    * insert SearchParam(#SHALL, "version", #token, http://hl7.org/fhir/SearchParameter/Library-version)
    * insert SearchParam(#SHALL, "experimental", #token, http://hl7.org/fhir/uv/sdc/SearchParameter/canonical-experimental)
    * insert SearchParam(#SHALL, "status", #token, http://hl7.org/fhir/SearchParameter/Library-status)
    * insert SearchParam(#SHALL, "description", #string, http://hl7.org/fhir/SearchParameter/Library-description)
    * insert SearchParam(#SHALL, "content-type", #token, http://hl7.org/fhir/SearchParameter/Library-content-type)
    * insert SearchParam(#SHALL, "type", #token, http://hl7.org/fhir/SearchParameter/Library-type)
    * insert SearchParam(#SHOULD, "date", #date, http://hl7.org/fhir/SearchParameter/Library-date)
    * insert SearchParam(#SHOULD, "publisher", #string, http://hl7.org/fhir/SearchParameter/Library-publisher)
    * insert SearchParam(#SHOULD, "context-type-quantity", #composite, http://hl7.org/fhir/SearchParameter/Library-context-type-quantity)
    * insert SearchParam(#SHOULD, "context-type-value", #composite, http://hl7.org/fhir/SearchParameter/Library-context-type-value)
    * insert SearchParam(#SHOULD, "effective", #date, http://hl7.org/fhir/SearchParameter/Library-effective)
    * insert SearchParam(#SHOULD, "title", #string, http://hl7.org/fhir/SearchParameter/Library-title)
    * insert SearchParam(#MAY, "jurisdiction", #token, http://hl7.org/fhir/SearchParameter/Library-jurisdiction)
  * insert CoreResource(StructureMap, #MAY, [[Allows managing maps relevant to population or extraction]])
    * insert Interaction(#SHALL, #search-type, "Allows discovery of existing maps for use in converting to or from the form")
    * insert Interaction(#SHALL, #create, "Allows definition of a new map for a form")
    * insert Interaction(#SHALL, #update, "Allows existing maps  referenced by a form to be maintained.  Note that certain types of updates may necessitate retiring the existing map and defining a new one.")
    * insert Interaction(#SHOULD, #delete, "Not all servers will support deletion of maps.  Status change to 'retired' will be more typical\, though deletion of draft maps may keep repositories cleaner.")
    * insert Interaction(#MAY, #read, "Allows retrieval of details if search does not or after a create or update if the server makes changes")
    * insert Interaction(#MAY, #history-instance, "Allows review of changes to a map over time")
    * insert Interaction(#MAY, #vread, "Allows retrieval of a historical version of a map")
    * insert SearchParam(#SHALL, "url", #uri, http://hl7.org/fhir/SearchParameter/conformance-url)
    * insert SearchParam(#SHALL, "version", #token, http://hl7.org/fhir/SearchParameter/conformance-version)
    * insert SearchParam(#SHALL, "experimental", #token, http://hl7.org/fhir/uv/sdc/SearchParameter/canonical-experimental)
    * insert SearchParam(#SHALL, "status", #token, http://hl7.org/fhir/SearchParameter/conformance-status)
    * insert SearchParam(#SHALL, "source", #reference, http://hl7.org/fhir/uv/sdc/SearchParameter/StructureMap-source)
    * insert SearchParam(#SHALL, "target", #reference, http://hl7.org/fhir/uv/sdc/SearchParameter/StructureMap-target)
    * insert SearchParam(#SHOULD, "date", #date, http://hl7.org/fhir/SearchParameter/conformance-date)
    * insert SearchParam(#SHOULD, "publisher", #string, http://hl7.org/fhir/SearchParameter/conformance-publisher)
    * insert SearchParam(#SHOULD, "context-type-quantity", #composite, http://hl7.org/fhir/SearchParameter/conformance-context-type-quantity)
    * insert SearchParam(#SHOULD, "context-type-value", #composite, http://hl7.org/fhir/SearchParameter/conformance-context-type-value)
    * insert SearchParam(#SHOULD, "title", #string, http://hl7.org/fhir/SearchParameter/conformance-title)
    * insert SearchParam(#MAY, "description", #string, http://hl7.org/fhir/SearchParameter/conformance-description)
    * insert SearchParam(#MAY, "jurisdiction", #token, http://hl7.org/fhir/SearchParameter/conformance-jurisdiction)
  * insert CoreResource(StructureDefinition, #MAY, [[Allows managing structures relevant to map-based population and/or map-based or definition-based extraction]])
    * insert Interaction(#SHALL, #search-type, "Allows discovery of existing structures")
    * insert Interaction(#SHALL, #create, "Allows definition of new structures for use with forms")
    * insert Interaction(#SHALL, #update, "Allows existing structures to be maintained.  Note that certain types of updates may necessitate retiring the existing structure and defining a new one.")
    * insert Interaction(#SHOULD, #delete, "Not all servers will support deletion of structures.  Status change to 'retired' will be more typical\, though deletion of draft structures may keep repositories cleaner.")
    * insert Interaction(#MAY, #read, "Allows retrieval of details if search does not or after a create or update if the server makes changes")
    * insert Interaction(#MAY, #history-instance, "Allows review of changes to a structure over time")
    * insert Interaction(#MAY, #vread, "Allows retrieval of a historical version of a structures")
    * insert SearchParam(#SHALL, "url", #uri, http://hl7.org/fhir/SearchParameter/conformance-url)
    * insert SearchParam(#SHALL, "version", #token, http://hl7.org/fhir/SearchParameter/conformance-version)
    * insert SearchParam(#SHALL, "experimental", #token, http://hl7.org/fhir/uv/sdc/SearchParameter/canonical-experimental)
    * insert SearchParam(#SHALL, "status", #token, http://hl7.org/fhir/SearchParameter/conformance-status)
    * insert SearchParam(#SHALL, "type", #uri, http://hl7.org/fhir/SearchParameter/StructureDefinition-type)
    * insert SearchParam(#SHALL, "derivation", #token, http://hl7.org/fhir/SearchParameter/StructureDefinition-derivation)
    * insert SearchParam(#SHALL, "kind", #token, http://hl7.org/fhir/SearchParameter/StructureDefinition-kind)
    * insert SearchParam(#SHOULD, "date", #date, http://hl7.org/fhir/SearchParameter/conformance-date)
    * insert SearchParam(#SHOULD, "publisher", #string, http://hl7.org/fhir/SearchParameter/conformance-publisher)
    * insert SearchParam(#SHOULD, "context-type-quantity", #composite, http://hl7.org/fhir/SearchParameter/conformance-context-type-quantity)
    * insert SearchParam(#SHOULD, "context-type-value", #composite, http://hl7.org/fhir/SearchParameter/conformance-context-type-value)
    * insert SearchParam(#SHOULD, "title", #string, http://hl7.org/fhir/SearchParameter/conformance-title)
    * insert SearchParam(#MAY, "description", #string, http://hl7.org/fhir/SearchParameter/conformance-description)
    * insert SearchParam(#MAY, "jurisdiction", #token, http://hl7.org/fhir/SearchParameter/conformance-jurisdiction)
  * insert CoreResource(ConceptMap, #MAY, [[Allows managing code maps relevant to population or extraction]])
    * insert Interaction(#SHALL, #search-type, "Allows discovery of existing maps for use in converting codes used the form")
    * insert Interaction(#SHALL, #create, "Allows definition of a new map for codes in a form")
    * insert Interaction(#SHALL, #update, "Allows existing maps used by forms to be maintained.  Note that certain types of updates may necessitate retiring the existing map and defining a new one.")
    * insert Interaction(#SHOULD, #delete, "Not all servers will support deletion of maps.  Status change to 'retired' will be more typical\, though deletion of draft maps may keep repositories cleaner.")
    * insert Interaction(#MAY, #read, "Allows retrieval of details if search does not or after a create or update if the server makes changes")
    * insert Interaction(#MAY, #history-instance, "Allows review of changes to a map over time")
    * insert Interaction(#MAY, #vread, "Allows retrieval of a historical version of a map")
    * insert SearchParam(#SHALL, "url", #uri, http://hl7.org/fhir/SearchParameter/conformance-url)
    * insert SearchParam(#SHALL, "version", #token, http://hl7.org/fhir/SearchParameter/conformance-version)
    * insert SearchParam(#SHALL, "experimental", #token, http://hl7.org/fhir/uv/sdc/SearchParameter/canonical-experimental)
    * insert SearchParam(#SHALL, "status", #token, http://hl7.org/fhir/SearchParameter/conformance-status)
    * insert SearchParam(#SHALL, "source-system", #uri, http://hl7.org/fhir/SearchParameter/ConceptMap-source-system)
    * insert SearchParam(#SHALL, "target-system", #uri, http://hl7.org/fhir/SearchParameter/ConceptMap-target-system)
    * insert SearchParam(#SHOULD, "date", #date, http://hl7.org/fhir/SearchParameter/conformance-date)
    * insert SearchParam(#SHOULD, "publisher", #string, http://hl7.org/fhir/SearchParameter/conformance-publisher)
    * insert SearchParam(#SHOULD, "context-type-quantity", #composite, http://hl7.org/fhir/SearchParameter/conformance-context-type-quantity)
    * insert SearchParam(#SHOULD, "context-type-value", #composite, http://hl7.org/fhir/SearchParameter/conformance-context-type-value)
    * insert SearchParam(#SHOULD, "title", #string, http://hl7.org/fhir/SearchParameter/conformance-title)
    * insert SearchParam(#SHALL, "source-uri", #reference, http://hl7.org/fhir/SearchParameter/ConceptMap-source-uri)
    * insert SearchParam(#SHALL, "target-uri", #reference, http://hl7.org/fhir/SearchParameter/ConceptMap-target-uri)
    * insert SearchParam(#MAY, "description", #string, http://hl7.org/fhir/SearchParameter/conformance-description)
    * insert SearchParam(#MAY, "jurisdiction", #token, http://hl7.org/fhir/SearchParameter/conformance-jurisdiction)
