Instance: sdc-form-manager
InstanceOf: CapabilityStatement
Title: "SDC Form Manager"
Description: "SDC Repository for forms"
Usage: #definition
* url = "http://hl7.org/fhir/uv/sdc/CapabilityStatement/sdc-form-manager"
* name = "SDCFormManager"
* title = "SDC Form Manager"
* status = #active
* date = "2014-07-06"
* description = "This profile defines the expected capabilities of the *SDC Form Manager* role when conforming to this implementation guide.  This role builds on the [SDC Form Fill Manager](CapabilityStatement-sdc-form-fill-manager.html) by adding the ability to create and maintain Questionnaires and their associated resources."
* kind = #requirements
* fhirVersion = #4.0.1
* format[+] = #xml
* format[+] = #json
* imports[+] = Canonical(sdc-form-fill-manager)
* rest
  * mode = #server
  * documentation = "The primary focus is being able to create and update [[[Questionnaire]]]s.  However, creation and maintenance of [[[ValueSet]]]s, [[[CodeSystem]]]s, [[[Library]]]s, and other associated resources is also potentially relevant, though in some cases these might be maintained on separate servers."
  * security.description = "Implementations must meet the [general security requirements](security.html) documented in this implementation guide.html."
  * insert SDCResource(Questionnaire, #SHALL, sdc-questionnaire, [[Form mamagers are responsible for creating and updating forms.]])
    * insert Interaction(#SHALL, #read, "Allows retrieval of a resource before or after performing a create or update.")
    * insert Interaction(#SHALL, #create, "Allows defining a new form.  Repositories requiring curation of submitted forms may require all new data elements to have a status of 'draft'.")
    * insert Interaction(#SHALL, #update, "Allows an existing form to be updated.  Servers may choose to prohibit certain types of edits\, instead requiring the creation of a new questionnaire (and potentially the retiring of the existing questionnaire\).  Servers may also limit who can change particular forms.")
    * insert Interaction(#SHOULD, #delete, "Allows removal of an existing form.  Servers may choose to not support deletions and instead require that the form's status be changed to 'retired'.  Other systems support deletions but limit them to forms meeting certain requirements.  E.g. only forms with a status of draft or only forms that have been retired for at least two years\, etc.")
    * insert SearchParam(#SHOULD, "definition", #uri, http://hl7.org/fhir/SearchParameter/Questionnaire-definition)
    * insert SearchParam(#SHOULD, "code", #token, http://hl7.org/fhir/SearchParameter/Questionnaire-code)
    * insert SearchParam(#SHOULD, "combo-code", #token, http://hl7.org/fhir/uv/sdc/SearchParameter/Questionnaire-combo-code)
    * insert SearchParam(#MAY, "assembled-from", #reference, http://hl7.org/fhir/uv/sdc/SearchParameter/questionnaire-assembled-from)
    * insert Operation(#MAY, "assemble", $assemble, [[Needed as part of the authoring process if modular questionnaires are used and assembly isn't done locally]])
  * insert SDCResource(ValueSet, #SHALL, sdc-valueset, [[Needed if Questionnaire valuesets will be stored on the form server as opposed to a separate terminology service.]])
    * insert Interaction(#SHALL, #read, "Allows retrieval of a resource before or after performing a create or update.")
    * insert Interaction(#SHALL, #create, "Allows definition of a new value set used by one or more questionnaires")
    * insert Interaction(#SHALL, #update, "Allows existing value sets referenced by one or more questionnaires to be maintained")
    * insert Interaction(#SHOULD, #delete, "Not all servers will support deletion of value sets.  Status change to 'retired' will be more typical\, though deletion of draft value sets may keep repositories cleaner.")
    * insert SearchParam(#SHALL, "status", #token,  http://hl7.org/fhir/SearchParameter/conformance-status)
    * insert SearchParam(#SHALL, "reference", #uri,  http://hl7.org/fhir/SearchParameter/ValueSet-reference)
    * insert SearchParam(#SHALL, "experimental", #token, http://hl7.org/fhir/uv/sdc/SearchParameter/canonical-experimental)
    * insert SearchParam(#SHOULD, "date", #date,  http://hl7.org/fhir/SearchParameter/conformance-date)
    * insert SearchParam(#SHOULD, "context-type-quantity", #composite, http://hl7.org/fhir/SearchParameter/conformance-context-type-quantity)
    * insert SearchParam(#SHOULD, "context-type-value", #composite, http://hl7.org/fhir/SearchParameter/conformance-context-type-value)
    * insert SearchParam(#SHOULD, "identifier", #token, http://hl7.org/fhir/SearchParameter/conformance-identifier)
    * insert SearchParam(#SHOULD, "title", #string, http://hl7.org/fhir/SearchParameter/conformance-title)
    * insert SearchParam(#MAY, "description", #string,  http://hl7.org/fhir/SearchParameter/conformance-description)
    * insert SearchParam(#MAY, "jurisdiction", #token, http://hl7.org/fhir/SearchParameter/conformance-jurisdiction)
    * insert SearchParam(#MAY, "publisher", #string, http://hl7.org/fhir/SearchParameter/conformance-publisher)
  * insert SDCResource(CodeSystem, #SHOULD, sdc-codesystem, [[Needed if Questionnaire codes will be stored on the form server as opposed to a separate terminology service.]])
    * insert Interaction(#SHALL, #read, "Allows retrieval of a resource before or after performing a create or update.")
    * insert Interaction(#SHALL, #create, "Allows definition of a new code system used by one or more questionnaires")
    * insert Interaction(#SHALL, #update, "Allows existing code systems referenced by one or more questionnaires to be maintained")
    * insert Interaction(#SHOULD, #delete, "Not all servers will support deletion of code systems.  Status change to 'retired' will be more typical\, though deletion of draft code systems may keep repositories cleaner.")
    * insert SearchParam(#SHALL, "status", #token,  http://hl7.org/fhir/SearchParameter/conformance-status)
    * insert SearchParam(#SHALL, "content-mode", #token, http://hl7.org/fhir/SearchParameter/CodeSystem-content-mode)
    * insert SearchParam(#SHALL, "experimental", #token, http://hl7.org/fhir/uv/sdc/SearchParameter/canonical-experimental)
    * insert SearchParam(#SHOULD, "date", #date,  http://hl7.org/fhir/SearchParameter/conformance-date)
    * insert SearchParam(#SHOULD, "publisher", #string, http://hl7.org/fhir/SearchParameter/conformance-publisher)
    * insert SearchParam(#SHOULD, "context-type-quantity", #composite, http://hl7.org/fhir/SearchParameter/conformance-context-type-quantity)
    * insert SearchParam(#SHOULD, "context-type-value", #composite, http://hl7.org/fhir/SearchParameter/conformance-context-type-value)
    * insert SearchParam(#SHOULD, "identifier", #token, http://hl7.org/fhir/SearchParameter/conformance-identifier)
    * insert SearchParam(#SHOULD, "supplements", #reference, http://hl7.org/fhir/SearchParameter/CodeSystem-supplements)
    * insert SearchParam(#SHOULD, "title", #string, http://hl7.org/fhir/SearchParameter/conformance-title)
    * insert SearchParam(#MAY, "description", #string,  http://hl7.org/fhir/SearchParameter/conformance-description)
    * insert SearchParam(#MAY, "jurisdiction", #token, http://hl7.org/fhir/SearchParameter/conformance-jurisdiction)
    * insert SearchParam(#MAY, "language", #token, http://hl7.org/fhir/SearchParameter/CodeSystem-language)
  * insert SDCResource(Library, #SHOULD, sdc-library, [[Allows managing libraries relevant to population\, extraction\, or other logic]])
    * insert Interaction(#SHALL, #read, "Allows retrieval of details if search does not or after a create or update if the server makes changes")
    * insert Interaction(#SHALL, #create, "Allows definition of a new library used by one or more questions")
    * insert Interaction(#SHALL, #update, "Allows existing libraries referenced by a form to be maintained.  Note that certain types of updates may necessitate retiring the existing library and defining a new one.")
    * insert Interaction(#SHOULD, #delete, "Not all servers will support deletion of libraries.  Status change to 'retired' will be more typical\, though deletion of draft libraries may keep repositories cleaner.")
    * insert SearchParam(#SHALL, "experimental", #token, http://hl7.org/fhir/uv/sdc/SearchParameter/canonical-experimental)
    * insert SearchParam(#SHALL, "status", #token, http://hl7.org/fhir/SearchParameter/Library-status)
    * insert SearchParam(#SHALL, "description", #string, http://hl7.org/fhir/SearchParameter/Library-description)
    * insert SearchParam(#SHALL, "content-type", #token, http://hl7.org/fhir/SearchParameter/Library-content-type)
    * insert SearchParam(#SHALL, "type", #token, http://hl7.org/fhir/SearchParameter/Library-type)
    * insert SearchParam(#SHOULD, "date", #date, http://hl7.org/fhir/SearchParameter/Library-date)
    * insert SearchParam(#SHOULD, "publisher", #string, http://hl7.org/fhir/SearchParameter/Library-publisher)
    * insert SearchParam(#SHOULD, "context-type-quantity", #composite, http://hl7.org/fhir/SearchParameter/Library-context-type-quantity)
    * insert SearchParam(#SHOULD, "context-type-value", #composite, http://hl7.org/fhir/SearchParameter/Library-context-type-value)
    * insert SearchParam(#SHOULD, "effective", #date, http://hl7.org/fhir/SearchParameter/Library-effective)
    * insert SearchParam(#SHOULD, "title", #string, http://hl7.org/fhir/SearchParameter/Library-title)
    * insert SearchParam(#MAY, "jurisdiction", #token, http://hl7.org/fhir/SearchParameter/Library-jurisdiction)

  * insert CoreResource(StructureMap, #MAY, [[Allows managing maps relevant to population or extraction]])
    * insert Interaction(#SHALL, #read, "Allows retrieval of details if search does not or after a create or update if the server makes changes")
    * insert Interaction(#SHALL, #create, "Allows definition of a new map for a form")
    * insert Interaction(#SHALL, #update, "Allows existing maps  referenced by a form to be maintained.  Note that certain types of updates may necessitate retiring the existing map and defining a new one.")
    * insert Interaction(#SHOULD, #delete, "Not all servers will support deletion of maps.  Status change to 'retired' will be more typical\, though deletion of draft maps may keep repositories cleaner.")
    * insert SearchParam(#SHALL, "experimental", #token, http://hl7.org/fhir/uv/sdc/SearchParameter/canonical-experimental)
    * insert SearchParam(#SHALL, "status", #token, http://hl7.org/fhir/SearchParameter/conformance-status)
    * insert SearchParam(#SHALL, "source", #reference, http://hl7.org/fhir/uv/sdc/SearchParameter/StructureMap-source)
    * insert SearchParam(#SHALL, "target", #reference, http://hl7.org/fhir/uv/sdc/SearchParameter/StructureMap-target)
    * insert SearchParam(#SHOULD, "date", #date, http://hl7.org/fhir/SearchParameter/conformance-date)
    * insert SearchParam(#SHOULD, "publisher", #string, http://hl7.org/fhir/SearchParameter/conformance-publisher)
    * insert SearchParam(#SHOULD, "context-type-quantity", #composite, http://hl7.org/fhir/SearchParameter/conformance-context-type-quantity)
    * insert SearchParam(#SHOULD, "context-type-value", #composite, http://hl7.org/fhir/SearchParameter/conformance-context-type-value)
    * insert SearchParam(#SHOULD, "title", #string, http://hl7.org/fhir/SearchParameter/conformance-title)
    * insert SearchParam(#MAY, "description", #string, http://hl7.org/fhir/SearchParameter/conformance-description)
    * insert SearchParam(#MAY, "jurisdiction", #token, http://hl7.org/fhir/SearchParameter/conformance-jurisdiction)
  * insert CoreResource(StructureDefinition, #MAY, [[Allows managing structures relevant to map-based population and/or map-based or definition-based extraction]])
    * insert Interaction(#SHALL, #read, "Allows retrieval of details if search does not or after a create or update if the server makes changes")
    * insert Interaction(#SHALL, #create, "Allows definition of new structures for use with forms")
    * insert Interaction(#SHALL, #update, "Allows existing structures to be maintained.  Note that certain types of updates may necessitate retiring the existing structure and defining a new one.")
    * insert Interaction(#SHOULD, #delete, "Not all servers will support deletion of structures.  Status change to 'retired' will be more typical\, though deletion of draft structures may keep repositories cleaner.")
    * insert SearchParam(#SHALL, "experimental", #token, http://hl7.org/fhir/uv/sdc/SearchParameter/canonical-experimental)
    * insert SearchParam(#SHALL, "status", #token, http://hl7.org/fhir/SearchParameter/conformance-status)
    * insert SearchParam(#SHALL, "type", #uri, http://hl7.org/fhir/SearchParameter/StructureDefinition-type)
    * insert SearchParam(#SHALL, "derivation", #token, http://hl7.org/fhir/SearchParameter/StructureDefinition-derivation)
    * insert SearchParam(#SHALL, "kind", #token, http://hl7.org/fhir/SearchParameter/StructureDefinition-kind)
    * insert SearchParam(#SHOULD, "date", #date, http://hl7.org/fhir/SearchParameter/conformance-date)
    * insert SearchParam(#SHOULD, "publisher", #string, http://hl7.org/fhir/SearchParameter/conformance-publisher)
    * insert SearchParam(#SHOULD, "context-type-quantity", #composite, http://hl7.org/fhir/SearchParameter/conformance-context-type-quantity)
    * insert SearchParam(#SHOULD, "context-type-value", #composite, http://hl7.org/fhir/SearchParameter/conformance-context-type-value)
    * insert SearchParam(#SHOULD, "title", #string, http://hl7.org/fhir/SearchParameter/conformance-title)
    * insert SearchParam(#MAY, "description", #string, http://hl7.org/fhir/SearchParameter/conformance-description)
    * insert SearchParam(#MAY, "jurisdiction", #token, http://hl7.org/fhir/SearchParameter/conformance-jurisdiction)
  * insert CoreResource(ConceptMap, #MAY, [[Allows managing code maps relevant to population or extraction]])
    * insert Interaction(#SHALL, #read, "Allows retrieval of details if search does not or after a create or update if the server makes changes")
    * insert Interaction(#SHALL, #create, "Allows definition of a new map for codes in a form")
    * insert Interaction(#SHALL, #update, "Allows existing maps used by forms to be maintained.  Note that certain types of updates may necessitate retiring the existing map and defining a new one.")
    * insert Interaction(#SHOULD, #delete, "Not all servers will support deletion of maps.  Status change to 'retired' will be more typical\, though deletion of draft maps may keep repositories cleaner.")
    * insert SearchParam(#SHALL, "experimental", #token, http://hl7.org/fhir/uv/sdc/SearchParameter/canonical-experimental)
    * insert SearchParam(#SHALL, "status", #token, http://hl7.org/fhir/SearchParameter/conformance-status)
    * insert SearchParam(#SHALL, "source-system", #uri, http://hl7.org/fhir/SearchParameter/ConceptMap-source-system)
    * insert SearchParam(#SHALL, "target-system", #uri, http://hl7.org/fhir/SearchParameter/ConceptMap-target-system)
    * insert SearchParam(#SHOULD, "date", #date, http://hl7.org/fhir/SearchParameter/conformance-date)
    * insert SearchParam(#SHOULD, "publisher", #string, http://hl7.org/fhir/SearchParameter/conformance-publisher)
    * insert SearchParam(#SHOULD, "context-type-quantity", #composite, http://hl7.org/fhir/SearchParameter/conformance-context-type-quantity)
    * insert SearchParam(#SHOULD, "context-type-value", #composite, http://hl7.org/fhir/SearchParameter/conformance-context-type-value)
    * insert SearchParam(#SHOULD, "title", #string, http://hl7.org/fhir/SearchParameter/conformance-title)
    * insert SearchParam(#SHALL, "source-uri", #reference, http://hl7.org/fhir/SearchParameter/ConceptMap-source-uri)
    * insert SearchParam(#SHALL, "target-uri", #reference, http://hl7.org/fhir/SearchParameter/ConceptMap-target-uri)
    * insert SearchParam(#MAY, "description", #string, http://hl7.org/fhir/SearchParameter/conformance-description)
    * insert SearchParam(#MAY, "jurisdiction", #token, http://hl7.org/fhir/SearchParameter/conformance-jurisdiction)
