Instance: populatehtml-response
InstanceOf: SDCParametersQuestionnairePopulateHtmlOut
Title: "Example $populate-html operation response"
Description: "Shows the response payload when invoking a populate-html operation"
Usage: #example
* parameter[0]
  * name = "form"
  * resource = HTMLBinary

Instance: HTMLBinary
InstanceOf: Binary
Usage: #inline
* contentType = #text/html
* data = "PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiPz4KPCFET0NUWVBFIGh0bWwgUFVCTElDICItLy9XM0MvL0RURCBYSFRNTCAxLjAgU3RyaWN0Ly9FTiIgCgkiaHR0cDovL3d3dy53My5vcmcvVFIveGh0bWwxL0RURC94aHRtbDEtc3RyaWN0LmR0ZCI+CjxodG1sIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8xOTk5L3hodG1sIiB4bWw6bGFuZz0iZW4iIGxhbmc9ImVuIj4KCTxoZWFkPgoJCTx0aXRsZT5VU1NHIEZhbWlseSBIaXN0b3J5PC90aXRsZT4KCTwvaGVhZD4KCTxib2R5PgoJCTxoMT5RdWVzdGlvbm5haXJlIGNvbnRlbnQ8L2gxPgoJCTxwPk5vcm1hbGx5IHRoaXMgd291bGQgYmUgYSBRdWVzdGlvbm5haXJlIHdpdGggYWN0aXZlIGlucHV0IGNvbnRyb2xzLCBhICdzdWJtaXQnIGJ1dHRvbiBhdCB0aGUgZW5kIGFuZCBlbWJlZGRlZCBKYXZhc2NyaXB0IHRoYXQgd291bGQgKHNlY3VyZWx5KSB0cmFuc21pdCB0aGUgY29udGVudCBvZiB0aGUgY29tcGxldGVkIGZvcm0gdG8gc29tZSBkZXNpcmVkIGVuZCBsb2NhdGlvbi4gIEhvd2V2ZXIsIEhMNyBwdWJsaWNhdGlvbiBydWxlcyBoYXZlIHRpZ2h0IGd1aWRlbGluZXMgb24gdGhlIHVzZSBvZiBKYXZhc2NyaXB0IGFuZCBvdGhlciBhY3RpdmUgY29udHJvbHMsIHNvIG5vIGZ1bmN0aW9uYWwgZXhhbXBsZSBpcyBwcm92aWRlZC4gIFRoaXMgZXhhbXBsZSBzaG91bGQsIGhvd2V2ZXIsIHN0aWxsIGluZGljYXRlIGhvdyBhbiBhcmJpdHJhcnkgSFRNTCBwYWdlIHRoYXQgY291bGQgYmUgcmVuZGVyZWQgaW4gYSBsb2NhbCBicm93c2VyIGNvdWxkIGJlIHRyYW5zbWl0dGVkIHVzaW5nIHRoZSBTREMgJHBvcHVsYXRlLWh0bWwgb3BlcmF0aW9uLjwvcD4KCTwvYm9keT4KPC9odG1sPgo="
